-- CareerOps completion schema
CREATE TABLE IF NOT EXISTS processing_runs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_type VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'running',
    correlation_id VARCHAR(100) NOT NULL,
    input_count INTEGER NOT NULL DEFAULT 0,
    output_count INTEGER NOT NULL DEFAULT 0,
    error_count INTEGER NOT NULL DEFAULT 0,
    summary TEXT NOT NULL DEFAULT '{}',
    error_message TEXT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS ix_processing_runs_run_type ON processing_runs(run_type);
CREATE INDEX IF NOT EXISTS ix_processing_runs_status ON processing_runs(status);
CREATE INDEX IF NOT EXISTS ix_processing_runs_correlation_id ON processing_runs(correlation_id);

CREATE TABLE IF NOT EXISTS audit_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(50) NOT NULL,
    entity_id INTEGER,
    action VARCHAR(100) NOT NULL,
    actor VARCHAR(100) NOT NULL DEFAULT 'system',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_audit_events_entity ON audit_events(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS ix_audit_events_action ON audit_events(action);

CREATE TABLE IF NOT EXISTS resume_documents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    document_type VARCHAR(30) NOT NULL DEFAULT 'master',
    version INTEGER NOT NULL DEFAULT 1,
    content TEXT NOT NULL,
    is_master BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_resume_documents_master ON resume_documents(is_master);

CREATE TABLE IF NOT EXISTS resume_drafts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id INTEGER NOT NULL REFERENCES jobs(id),
    master_resume_id INTEGER NOT NULL REFERENCES resume_documents(id),
    status VARCHAR(30) NOT NULL DEFAULT 'draft',
    content TEXT NOT NULL,
    change_plan TEXT NOT NULL DEFAULT '[]',
    matched_keywords TEXT NOT NULL DEFAULT '[]',
    missing_keywords TEXT NOT NULL DEFAULT '[]',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    approved_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS ix_resume_drafts_job_id ON resume_drafts(job_id);
CREATE INDEX IF NOT EXISTS ix_resume_drafts_status ON resume_drafts(status);
